Update build.yml to include BusyBox CAN patch
Add patch for BusyBox CAN compatibility in build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build firmware
+Aname: Build firmware
 
 on:
   workflow_dispatch:
@@ -29,6 +29,16 @@ jobs:
         git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO"
         git -C padavan-ng checkout "$PADAVAN_COMMIT"
         wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -
+
+    - name: Patch BusyBox CAN compatibility
+      run: |
+        file="padavan-ng/trunk/user/busybox/busybox-1.37.0/networking/libiproute/iplink.c"
+        [[ -f "$file" ]] || { echo "BusyBox iplink.c not found: $file"; exit 1; }
+
+        perl -0pi -e 's/\n(\s*flag = CAN_CTRLMODE_FD;\n\s*break;)/\n#ifdef CAN_CTRLMODE_FD$1\n#endif/s' "$file"
+        perl -0pi -e 's/\n(\s*flag = CAN_CTRLMODE_FD_NON_ISO;\n\s*break;)/\n#ifdef CAN_CTRLMODE_FD_NON_ISO$1\n#endif/s' "$file"
+        perl -0pi -e 's/\n(\s*flag = CAN_CTRLMODE_PRESUME_ACK;\n\s*break;)/\n#ifdef CAN_CTRLMODE_PRESUME_ACK$1\n#endif/s' "$file"
+        perl -0pi -e 's/(\s*addattr_l\(&req\.n, sizeof\(req\), IFLA_CAN_TERMINATION, &val, sizeof\(val\)\);)/#ifdef IFLA_CAN_TERMINATION\n$1\n#endif/' "$file"
 
     - name: Install themes
       run: |
